# 해당 펄미션 보유시 금지템 사용가능, /금지템관리 명령어 사용가능
Permission: banitem.admin

# 금지템 GUI 이름
RightClickBannedItemsGUI: 금지템:[&6우클릭&r]
CraftBannedItemsGUI: 금지템:[&a조합&r]

# 금지템 사용했을 때의 메시지
RightClickBannedMessage: '&6놀이터 &f｜ &c해당 아이템은 사용할 수 없습니다.'
CraftBannedMessage: '&6놀이터 &f｜ &c해당 아이템은 조합할 수 없습니다.'

# /금지템관리 명령어 메시지
AdminHelpMessage:
  - ' '
  - '&6놀이터 &f｜ &c/금지템관리 우클릭 &f- 우클릭을 금지하는 아이템을 설정합니다.'
  - '&6놀이터 &f｜ &c/금지템관리 조합 &f- 조합을 금지하는 아이템을 설정합니다.'
WrongAdminCommand: '&6놀이터 &f｜ &c해당 명령어가 존재하지 않습니다. &f/금지템관리'
OpenedRightClickBannedItemsGUI: '&6놀이터 &f｜ 금지템:[&6우클릭&f] 설정창을 열었습니다. 페이지를 넘기거나 닫으면 값을 저장합니다.'
OpenedCraftBannedItemsGUI: '&6놀이터 &f｜ 금지템:[&a조합&f] 설정창을 열었습니다. 페이지를 넘기거나 닫으면 값을 저장합니다.'
AnotherSettingRightClickBannedItems: '&6놀이터 &f｜ 현재 다른 플레이어:[&a%player%&f]가 금지템:[&6우클릭&f]을 설정하고 있습니다.'
AnotherSettingCraftBannedItems: '&6놀이터 &f｜ 현재 다른 플레이어:[&a%player%&f]가 금지템:[&a조합&f]을 설정하고 있습니다.'

PreviousItem:
  Name: '&c[ &f이전 페이지 &c]'
  Lore:
    - '&6▶ &f클릭 시 이전페이지로 이동합니다.'

NextItem:
  Name: '&a[ &f다음 페이지 &a]'
  Lore:
    - '&6▶ &f클릭 시 다음페이지로 이동합니다.'

PreventClickItem:
  Name: '&c클릭 방지'
  Lore:
    - '&6▶ &f클릭 방지를 위한 아이템입니다.'

ShowPageItem:
  Name: '&6[ &f현재 페이지 &6]'
  Lore:
    - '&6▶ &f%page% 페이지'