name: ST-BanItem
version: 2.1
author: STuuDENT
main: com.stuudent.BanItem.BanItemCore
description: 자작 금지템 플러그인 created by STuuDENT
default-permission: true

commands:
  사용금지템:
    description: Show Right Click Banned Items to Player.
  조합금지템:
    description: Show Craft Banned Items to Player.
  금지템관리:
    permission: banitem.admin
    description: You Can Set BanItem through this Commands.